# -*- coding: utf-8 -*-
"""graph-colouring and 4-queens using z3 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uHY-t7xGUZM9eiHeR6R44B3vCHqQjcOi
"""

!pip install z3-solver

from z3 import *

#1=RED 2=BLUE 3=GREEN
WT=Int('WT')
NT=Int('NT')
SA=Int('SA')
Q=Int('Q')
NSW=Int('NSW')
V=Int('V')
T=Int('T')
solve(WT>0,NT>0,SA>0,Q>0,NSW>0,V>0,T>0,WT<4,NT<4,SA<4,Q<4,NSW<4,V<4,T<4,WT!=NT,WT!=SA,NT!=SA,NT!=Q,SA!=Q,SA!=NSW,SA!=V,Q!=NSW,NSW!=V)

Q = [ Int(f"Q{row + 1}") for row in range(4) ]
val_c = [ And(1 <= Q[row], Q[row] <= 4) for row in range(4) ]
col_c = [ Distinct(Q) ]
diag_c = [ If(i == j,True,And(Q[i] - Q[j] != i - j, Q[i] - Q[j] != j - i)) for i in range(4) for j in range(i) ] #no attack happpens diagonally
solve(val_c + col_c + diag_c)